# Generated by Django 3.1.1 on 2020-12-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('ID_Peli', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.DurationField()),
                ('descripcion', models.TextField()),
                ('detalle', models.TextField()),
                ('genero', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('fechaComienzo', models.DateField()),
                ('fechaFinalizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('ID_Sala', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('fila', models.CharField(max_length=50)),
                ('asientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('ID_Proye', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.BooleanField()),
                ('pelicula', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionCine.pelicula')),
                ('sala', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionCine.salas')),
            ],
        ),
        migrations.CreateModel(
            name='Butacas',
            fields=[
                ('ID_butacas', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fila', models.CharField(max_length=50)),
                ('asiento', models.IntegerField()),
                ('proyeccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionCine.proyeccion')),
            ],
        ),
    ]
