# Generated by Django 3.1.1 on 2020-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='fila',
            field=models.IntegerField(),
        ),
    ]
