# Generated by Django 3.1.4 on 2020-12-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCine', '0002_auto_20201201_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fechaComienzo',
            field=models.DateField(verbose_name='Fecha de comienzo'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fechaFinalizacion',
            field=models.DateField(verbose_name='Fecha de Finalizacion'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de finalizacion'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
