# Generated by Django 3.1.4 on 2020-12-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCine', '0003_auto_20201209_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butacas',
            name='fila',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='butacas',
            name='proyeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionCine.proyeccion'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionCine.pelicula'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionCine.salas'),
        ),
    ]
