# Generated by Django 3.1.4 on 2021-01-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCine', '0006_auto_20210120_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion',
        ),
    ]
