# Generated by Django 3.1.4 on 2021-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCine', '0007_remove_pelicula_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
    ]
